[bash]
allow = [
    "cargo *",
    "tail *",
    "git *",
    "head *",
    "mkdir *",
    "cd *",
    "echo *",
    "wc *",
    "python3 *",
    "touch *",
    "cat *",
    "rustc *",
    "readlink *",
    "file *",
    "gcc *",
    "timeout *",
    "grep *",
    "capsh *",
    "unshare *",
    "dmesg *",
    "aa-status *",
    "getenforce *",
    "uname *",
    "which *",
    "ls *",
    "sysctl *",
    "strings *",
    "mount *",
    "findmnt *",
    "stat *",
    "true *",
    "ldd *",
    "readelf *",
    "sed *",
    "find *",
    "sudo *",
    "rm *",
    "for *",
    "sort *",
    "pwd *",
    "mv *",
]

]
